### PR TITLE
Fix package metadata

### PR DESCRIPTION
**Pull request by KarimElgammal**
This PR fixes the issue where the package was being installed as "UNKNOWN" by adding the setup.py configuration. The changes include:

- Properly setting the name, version, and other metadata in setup.py.
- Ensuring compatibility with the pyproject.toml.
- Additionally, I updated the README to include a simpler installation command:

```
pip install git+https://github.com/mrossinek/qiskit-nature-cp2k.git
```
This makes it easier for users to install directly from the repository.

### CODE REVIEW

**Review by mrossinek — COMMENTED** [review]
The `pyproject.toml` file should be sufficient. I will not be adding a redundant `setup.py` file. Please provide an issue description with reproducible steps to show the installation problem that you have without this PR in place.

**Comment by KarimElgammal** [comment]
> The `pyproject.toml` file should be sufficient. I will not be adding a redundant `setup.py` file. Please provide an issue description with reproducible steps to show the installation problem that you have without this PR in place.

when I do 'pip install .' I get the package name as 'UNKNOWN' after 'pip list', then I can't do imports as 'from qiskit_nature_cp2k'

**Comment by mrossinek** [comment]
> when I do 'pip install .' I get the package name as 'UNKNOWN' after 'pip list', then I can't do imports as 'from qiskit_nature_cp2k'

- what Python and `pip` versions do you use?
- what operating system are you on?
- does `pip install .` produce any output? If so, please provide that.
- the output of `pip list` or `pip freeze` after the installation completed would be good, too

Does this problem persist in a clean Python virtual environment? Thinking about environment, do you use `venv`, `virtualenv` or some other environment wrapper?

**Comment by KarimElgammal** [comment]
I am so sorry for the confusion, 
the 'UNKNOWN' happens only when I use:
pip install git+https://github.com/mrossinek/qiskit-nature-cp2k.git

when running it according to the instructions in README, it successfully install and no need for this branch, I will close then

Kindly find the answers below:
- 'Python 3.12.2'
- pip 24.2
- Ubuntu 24.04 LTS
- steps:
`git clone https://github.com/mrossinek/qiskit-nature-cp2k.git`
`cd qiskit-nature-cp2k`
`pip install  .`
- I got:
Successfully installed dill-0.3.8 h5py-3.11.0 mpmath-1.3.0 numpy-2.0.1 pbr-6.0.0 psutil-6.0.0 python-dateutil-2.9.0.post0 qiskit-1.1.2 qiskit-algorithms-0.3.0 qiskit-nature-0.7.2 qiskit_nature_cp2k-0.0.1 rustworkx-0.15.1 scipy-1.14.0 setuptools-72.2.0 six-1.16.0 stevedore-5.2.0 symengine-0.11.0 sympy-1.13.2 typing-extensions-4.12.2

- when I run pip list, I get:
Package            Version
------------------ -----------
dill               0.3.8
h5py               3.11.0
mpmath             1.3.0
numpy              2.0.1
pbr                6.0.0
pip                24.2
psutil             6.0.0
python-dateutil    2.9.0.post0
qiskit             1.1.2
qiskit-algorithms  0.3.0
qiskit-nature      0.7.2
qiskit_nature_cp2k 0.0.1
rustworkx          0.15.1
scipy              1.14.0
setuptools         72.2.0
six                1.16.0
stevedore          5.2.0
symengine          0.11.0
sympy              1.13.2
typing_extensions  4.12.2

- Clean environment using pyenv virtualenv ('pyenv virtualenv 3.12.2 testing-qiskit-nature-cp2k')

**Comment by KarimElgammal** [comment]
the 'UNKNOWN' happens only when I use:
pip install git+https://github.com/mrossinek/qiskit-nature-cp2k.git

**Pull request closed without merging**
